### ISSUE TITLE
Peak Detection Circuit Specs

### ISSUE THREAD

**Issue by PlanetMacro** [neilh10/MindMirrorEeg#1]
As explained [here](http://mindmirroreeg.com/w/equipment/mm-models.htm), The Analog MindMirror uses a peak detect circuit, which I can not find any description for.

Can you point me to the part of the code where this circuit is simulated? Also is there any technical description available, of the original circuit?

**Comment by neilh10** [comment]
well sounds like you are doing testing. Sometime if you can take a few steps then its learning to walk by yourself.   Its "schematic", its done in software so there is stable visuals!

**Comment by PlanetMacro** [comment]
what?
